spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

      routes:
        # ==========================================
        # 01. AUTH SERVICE ROUTES
        # ==========================================
        - id: auth-service-docs
          uri: ${userservice.base-uri:http://localhost:8081}
          order: -1
          predicates:
            - Path=/auth/v3/api-docs
          filters:
            - RewritePath=/auth/(?<segment>.*), /${segment}

        - id: auth-service-route
          uri: ${authservice.base-uri:http://localhost:8081}
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/(?<segment>.*), /${segment}

        # ==========================================
        # 02. USER SERVICE ROUTES
        # ==========================================
        - id: user-service-docs
          uri: ${userservice.base-uri:http://localhost:8082}
          order: -1
          predicates:
            - Path=/user/v3/api-docs
          filters:
            - RewritePath=/user/(?<segment>.*), /${segment}

        - id: user-service-route
          uri: ${userservice.base-uri:http://localhost:8082}
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<segment>.*), /${segment}
            - TokenRelay

        # ==========================================
        # 03. BUS SERVICE ROUTES
        # ==========================================
        - id: bus-service-docs
          uri: ${busService.base-uri:http://localhost:8086}
          order: -1
          predicates:
            - Path=/bus/v3/api-docs
          filters:
            - RewritePath=/bus/(?<segment>.*), /${segment}

        - id: bus-service-route
          uri: ${busService.base-uri:http://localhost:8086}
          predicates:
            - Path=/bus/**
          filters:
            - RewritePath=/bus/(?<segment>.*), /${segment}

        # ==========================================
        # 04. BOOKING SERVICE ROUTES
        # ==========================================
        - id: booking-service-docs
          uri: ${bookingService.base-uri:http://localhost:8087}
          order: -1
          predicates:
            - Path=/booking/v3/api-docs
          filters:
            - RewritePath=/booking/(?<segment>.*), /${segment}

        - id: booking-service-route
          uri: ${bookingService.base-uri:http://localhost:8087}
          predicates:
            - Path=/booking/**
          filters:
            - RewritePath=/booking/(?<segment>.*), /${segment}

        # ==========================================
        # 05. TRANSACTION SERVICE ROUTES
        # ==========================================
        - id: transaction-service-docs
          uri: ${transactionservice.base-uri:http://localhost:8085}
          order: -1
          predicates:
            - Path=/txn/v3/api-docs
          filters:
            - RewritePath=/txn/(?<segment>.*), /${segment}

        - id: transaction-service-route
          uri: ${transactionservice.base-uri:http://localhost:8085}
          predicates:
            - Path=/txn/**
          filters:
            - RewritePath=/txn/(?<segment>.*), /${segment}
            - TokenRelay



# --- SWAGGER UI AGGREGATION ---
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    urls:
      - name: 01. Auth Service
        url: /auth/v3/api-docs
      - name: 02. User Service
        url: /user/v3/api-docs
      - name: 03. Bus Service
        url: /bus/v3/api-docs
      - name: 04. Booking Service
        url: /booking/v3/api-docs
      - name: 05. Transaction Service
        url: /txn/v3/api-docs
    oauth:
      client-id: obtb-api-gateway
      client-secret: obtb-api-gateway-secret
      use-pkce-with-authorization-code-grant: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.security: DEBUG